version: '3.7'
services:
    db:
        image: mysql:latest
        container_name: AddressBook
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
            MYSQL_ROOT_PASSWORD: myrootpassword
        ports:
            - 3308:3306